# Site settings
title: UAVCAN
email: uavcan@googlegroups.com
description: Legacy UAVCAN v0 website. Not recommended for new designs.
baseurl: ""
url: "https://legacy.uavcan.org"
github_username: UAVCAN

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - "Specification/dsdl/*.md"
  - "Specification/dsdl/uavcan/*.md"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
