# Site settings
title: UAVCAN
email: uavcan@googlegroups.com
description: >
  UAVCAN is a lightweight protocol designed for reliable communication in aerospace
  and robotic applications via CAN bus.
baseurl: ""
url: "http://uavcan.org"
github_username: UAVCAN

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
